// Automatisch generierter Code. Nicht bearbeiten.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image3":
            case "meinBild1":return img`
d d d d d d d d d d d d d d d d 
d d d 1 1 d d d d d d d d b d d 
d d d 1 1 d d d d d d d d d d d 
d d d d d d d d d d d d d d d d 
d d b d d d d d d b b d d d d d 
d d d d d d d d d b b d d d d d 
d d d d d d d d d d d d d d d d 
d d d d d d d d d d d d d d d d 
d d d d d b d d d d d d d d d d 
d d d d d d d d d d d d d d d d 
d d d d d d d d d d d d d d d d 
1 1 d d d d d d d d d d d d d d 
1 1 d d d d d d d d d d b d d d 
d d d d d d 1 d d d d d d d d d 
d d d d d d d d d d d d d d d d 
d d d d d d d d d d d d d d b d 
`;
            case "j`NCp,CyKW4XJl7fC]o,":
            case "Normal":return img`
......ffff..............
....fff22fff............
...fff2222fff...........
..fffeeeeeefff..........
..ffe222222eef..........
..fe2ffffff2ef..........
..ffffeeeeffff......ccc.
.ffefbf44fbfeff....cddc.
.ffefbf44fbfeff...cddc..
.fee4dddddd4eef.ccddc...
fdfeeddddd4eeffecddc....
fbffee4444ee4fddccc.....
fbf4f222222f1edde.......
fcf.f222222f44ee........
.ff.f445544f............
....ffffffff............
.....ff..ff.............
........................
........................
........................
........................
........................
........................
........................
`;
            case "image2":
            case "Attack Left":return img`
...............ff.......
.............ff2ffff....
............ff2feeeeff..
...........ff22feeeeeff.
...........feeeeffeeeef.
..........fe2222eefffff.
..........f2effff222efff
..........fffeeeffffffff
..........fee44fbe44efef
...........feddfb4d4eef.
..........c.eeddd4eeef..
....ccccccceddee2222f...
.....dddddcedd44e444f...
......ccccc.eeeefffff...
..........c...ffffffff..
...............ff..fff..
........................
........................
........................
........................
........................
........................
........................
........................
`;
            case "image4":
            case "Attack Right":return img`
.......ff...............
....ffff2ff.............
..ffeeeef2ff............
.ffeeeeef22ff...........
.feeeeffeeeef...........
.fffffee2222ef..........
fffe222ffffe2f..........
ffffffffeeefff..........
fefe44ebf44eef..........
.fee4d4bfddef...........
..feee4dddee.c..........
...f2222eeddeccccccc....
...f444e44ddecddddd.....
...fffffeeee.ccccc......
..ffffffff...c..........
..fff..ff...............
........................
........................
........................
........................
........................
........................
........................
........................
`;
            case "image6":
            case "Attack Up":return img`
............c1c.........
............c1c.........
.......ff...c1c.........
.....ff22ff.c1c.........
...fff2222ffc1c.........
..fff222222cc1cc........
..fff222222fccc.........
..feeeeeeeeeeff.........
.ffe22222222eff.........
.fffffeeeefffff.........
fdfeffffffffeff.........
fbfe4ffffff4ef..........
fbffefffff4efe..........
fcfef22222f4e...........
.ff4fffffff4e...........
....fffffff.............
.....fffff..............
........................
........................
........................
........................
........................
........................
........................
`;
            case "image5":
            case "Attack Down":return img`
........................
........................
.......ff...............
.....ff22ff.............
...fff2222fff...........
..fff222222fff..........
..fff222222fff..........
..feeeeeeeeeeff.........
.ffe22222222eff.........
.fffffeeeefffff.........
fdfefbf44fbfeff.........
fbfe41fddf14ef..........
fbffe4dddd4efe..........
fcfef22222f4e...........
.ff4f44554f4e...........
....ffffffdde...........
.....ffffedde...........
..........ee............
.........ccc............
........cc1cc...........
.........c1c............
.........c1c............
.........c1c............
.........c1c............
`;
            case "image1":
            case "skellyFront":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Automatisch generierter Code. Nicht bearbeiten.
